spring.application.name=docker-manager
docker.socket.path=unix:///var/run/docker.sock
# if you are using Windows, uncomment the following line and comment the above line
# docker.socket.path=npipe:////./pipe/docker_engine
